In [1]:
import os
import numpy

In [2]:
file_location = os.path.join('data', 'water.xyz') #file path

In [6]:
#Tabular data so
xyz_file = numpy.genfromtxt(fname = file_location, dtype = 'unicode') #Mixed data type #got multiple (different)
#columns , should have been one for first... and so on, expecting same number of columns for each row

ValueError: Some errors were detected !
    Line #2 (got 3 columns instead of 1)
    Line #3 (got 4 columns instead of 1)
    Line #4 (got 4 columns instead of 1)
    Line #5 (got 4 columns instead of 1)

In [7]:
xyz_file = numpy.genfromtxt(fname = file_location, dtype = 'unicode', skip_header=2) 

In [8]:
xyz_file

array([['O', '0.000000', '-0.007156', '0.965491'],
       ['H1', '-0.000000', '0.001486', '-0.003471'],
       ['H2', '0.000000', '0.931026', '1.207929']], dtype='<U9')

In [9]:
print(xyz_file)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [10]:
symbols = xyz_file[:, 0]

In [11]:
symbols

array(['O', 'H1', 'H2'], dtype='<U9')

In [14]:
coordinates = xyz_file[:, 1:]

In [15]:
coordinates

array([['0.000000', '-0.007156', '0.965491'],
       ['-0.000000', '0.001486', '-0.003471'],
       ['0.000000', '0.931026', '1.207929']], dtype='<U9')

In [19]:
coordinates = coordinates.astype(numpy.float) # Recasting coordinates as float

<ipython-input-19-a3bbda50338e>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  coordinates = coordinates.astype(numpy.float) # Recasting coordinates as float


In [20]:
coordinates

array([[ 0.      , -0.007156,  0.965491],
       [-0.      ,  0.001486, -0.003471],
       [ 0.      ,  0.931026,  1.207929]])

In [21]:
coordinates.dtype

dtype('float64')

In [22]:
# One for loop to count over atom1 and another for loop to count over atom2
# we need the number of atoms

In [23]:
num_atoms = len(coordinates)

In [24]:
num_atoms

3

In [30]:
for num1 in range(num_atoms):
    for num2 in range(num_atoms): #print(num1, num2) 0 0 , 0 1, 0 2, 1 0, 1 1, 1 2, 2 0, 2 1, 2 2
        x_distance = coordinates[num1, 0] - coordinates[num2, 0]# row number is atom number 1 or 2, x coordinate only on 0 index
        y_distance = coordinates[num1, 1] - coordinates[num2, 1]
        z_distance = coordinates[num1, 2] - coordinates[num2, 2]  
        distance = numpy.sqrt(x_distance ** 2 + y_distance ** 2 + z_distance ** 2)
        print(f'{symbols[num1]} to {symbols[num2]} : {distance:.3f}')
        

O to O : 0.000
O to H1 : 0.969
O to H2 : 0.969
H1 to O : 0.969
H1 to H1 : 0.000
H1 to H2 : 1.527
H2 to O : 0.969
H2 to H1 : 1.527
H2 to H2 : 0.000


In [31]:
for num1 in range(num_atoms):
    for num2 in range(num_atoms): #print(num1, num2) 0 0 , 0 1, 0 2, 1 0, 1 1, 1 2, 2 0, 2 1, 2 2
        if num1 != num2:
            x_distance = coordinates[num1, 0] - coordinates[num2, 0]# row number is atom number 1 or 2, x coordinate only on 0 index
            y_distance = coordinates[num1, 1] - coordinates[num2, 1]
            z_distance = coordinates[num1, 2] - coordinates[num2, 2]  
            distance = numpy.sqrt(x_distance ** 2 + y_distance ** 2 + z_distance ** 2)
            if distance < 1.5:
                print(f'{symbols[num1]} to {symbols[num2]} : {distance:.3f}')
        

O to H1 : 0.969
O to H2 : 0.969
H1 to O : 0.969
H2 to O : 0.969


In [38]:
for num1 in range(num_atoms):
    for num2 in range(num_atoms): #print(num1, num2) 0 0 , 0 1, 0 2, 1 0, 1 1, 1 2, 2 0, 2 1, 2 2
        if num1 < num2:
            x_distance = coordinates[num1, 0] - coordinates[num2, 0]# row number is atom number 1 or 2, x coordinate only on 0 index
            y_distance = coordinates[num1, 1] - coordinates[num2, 1]
            z_distance = coordinates[num1, 2] - coordinates[num2, 2]  
            distance = numpy.sqrt(x_distance ** 2 + y_distance ** 2 + z_distance ** 2)
            if distance < 1.5 and distance > 0:
                
                print(f'{symbols[num1]} to {symbols[num2]} : {distance:.3f}')
        

O to H1 : 0.969
O to H2 : 0.969


In [35]:
# O to H1 and O H1 to O are same,so
# num1 < num2 check Look 0 1 and 0 2

### Writing and using functions (refactoring, or rewriting the code to make it better)

In [39]:
#def function_name(parameters):
#    ** Body of your function **
#    ** write code using the parameters to calculate something **
    
#    return value_to return
    
    
    
    
    

In [45]:
def calculate_distance(coords1, coords2):
    x_distance = coords1[0] - coords2[0]
    y_distance = coords1[1] - coords2[1]
    z_distance = coords1[2] - coords2[2]
    
    distance = numpy.sqrt(x_distance ** 2 + y_distance ** 2 + z_distance ** 2)
    return distance

In [46]:
calculate_distance([0,0,0], [0,0,1])

1.0

In [47]:
calculate_distance([0,0,0], [1,1,1])

1.7320508075688772

In [48]:
for num1 in range(num_atoms):
    for num2 in range(num_atoms): #print(num1, num2) 0 0 , 0 1, 0 2, 1 0, 1 1, 1 2, 2 0, 2 1, 2 2
        if num1 < num2:
            distance = calculate_distance(coordinates[num1], coordinates[num2])
            
            if distance < 1.5 and distance > 0:
                
                print(f'{symbols[num1]} to {symbols[num2]} : {distance:.3f}')
        

O to H1 : 0.969
O to H2 : 0.969


In [49]:
# write a code to check and see if a distance is a bond

In [56]:
def bond_check(atom_distance):
    if atom_distance > 0 and atom_distance < 1.5:
        return True
    else:
        return False


In [57]:
bond_check(1.7)

False

In [58]:
bond_check(1.2)

True

In [61]:
def bond_check(atom_distance):
    minimum = float(input("Enter the minimum bond length "))
    maximum = float(input("Enter the maximum bond length "))
    if atom_distance > minimum and atom_distance < maximum:
        return True
    else:
        return False


In [64]:
bond_check(1.2)

Enter the minimum bond length 0.3
Enter the maximum bond length 1.1


False

In [68]:
#This is the correct one
def bond_check(atom_distance, minimum_length = 0, maximum_length = 1.5):
   
    if atom_distance > minimum_length and atom_distance < maximum_length:
        return True
    else:
        return False


In [66]:
bond_check(1.2, 0.4, 2)

True

In [67]:
bond_check(1.7, 0, 2)

True

In [69]:
bond_check(1.7)

False

In [70]:
bond_check(1.7, maximum_length=2)

True

In [71]:
#how users know what arguments, parameters

In [73]:
help(bond_check) # we did not write help for users, documentation

Help on function bond_check in module __main__:

bond_check(atom_distance, minimum_length=0, maximum_length=1.5)
    #This is the correct one



In [74]:
#This is the correct one
def bond_check(atom_distance, minimum_length = 0, maximum_length = 1.5):
    """
    Checks if a distance is a bond based on a minimum and a maximum
    Inputs : distance, minimum length for bond, maximum length for bond
    Default: minimum : 0, maximum : 0
    
    
    """
   
    if atom_distance > minimum_length and atom_distance < maximum_length:
        return True
    else:
        return False


In [75]:
help(bond_check)

Help on function bond_check in module __main__:

bond_check(atom_distance, minimum_length=0, maximum_length=1.5)
    Checks if a distance is a bond based on a minimum and a maximum
    Inputs : distance, minimum length for bond, maximum length for bond
    Default: minimum : 0, maximum : 0



In [77]:
for num1 in range(num_atoms):
    for num2 in range(num_atoms): #print(num1, num2) 0 0 , 0 1, 0 2, 1 0, 1 1, 1 2, 2 0, 2 1, 2 2
        if num1 < num2:
            distance = calculate_distance(coordinates[num1], coordinates[num2])
            
            if bond_check(distance) is True:
                print(f'{symbols[num1]} to {symbols[num2]} : {distance:.3f}')
        

O to H1 : 0.969
O to H2 : 0.969


In [78]:
# write a new function called open_xyz that opens and processes the xyz file, 
# function should accept filepath (os path outside)

In [81]:
def open_xyz(filepath):
    xyz_file = numpy.genfromtxt(fname = filepath, dtype = 'unicode', skip_header=2) 
    symbols = xyz_file[:, 0]
    coordinates = xyz_file[:, 1:]
    coordinates = coordinates.astype(float)
    return coordinates
    

In [82]:
open_xyz(file_location)

array([[ 0.      , -0.007156,  0.965491],
       [-0.      ,  0.001486, -0.003471],
       [ 0.      ,  0.931026,  1.207929]])

In [87]:
# Correct version
def open_xyz(filename):
    """
    This function opens a standard xyz file.
    It returns the symbols as strings, and the coordinates as floats
    """
    xyz_file = numpy.genfromtxt(fname = filename, dtype = 'unicode', skip_header=2) 
    symbols = xyz_file[:, 0]
    coordinates = xyz_file[:, 1:]
    coordinates = coordinates.astype(float)
    return symbols, coordinates
    

In [86]:
open_xyz(file_location)

(array(['O', 'H1', 'H2'], dtype='<U9'),
 array([[ 0.      , -0.007156,  0.965491],
        [-0.      ,  0.001486, -0.003471],
        [ 0.      ,  0.931026,  1.207929]]))

In [89]:
#imports of library
import os
import numpy

# Write all custom function definitions
def calculate_distance(coords1, coords2):
    x_distance = coords1[0] - coords2[0]
    y_distance = coords1[1] - coords2[1]
    z_distance = coords1[2] - coords2[2]
    
    distance = numpy.sqrt(x_distance ** 2 + y_distance ** 2 + z_distance ** 2)
    return distance

def bond_check(atom_distance, minimum_length = 0, maximum_length = 1.5):
    """
    Checks if a distance is a bond based on a minimum and a maximum
    Inputs : distance, minimum length for bond, maximum length for bond
    Default: minimum : 0, maximum : 0
    
    
    """
   
    if atom_distance > minimum_length and atom_distance < maximum_length:
        return True
    else:
        return False
    
def open_xyz(filename):
    """
    This function opens a standard xyz file.
    It returns the symbols as strings, and the coordinates as floats
    """
    xyz_file = numpy.genfromtxt(fname = filename, dtype = 'unicode', skip_header=2) 
    symbols = xyz_file[:, 0]
    coordinates = xyz_file[:, 1:]
    coordinates = coordinates.astype(float)
    return symbols, coordinates


#Now, write coordinates

file_location = os.path.join('data', 'water.xyz')

symbols, coordinates = open_xyz(file_location)

num_atoms = len(symbols)

for num1 in range(num_atoms):
    for num2 in range(num_atoms):
         if num1 < num2:
                distance = calculate_distance(coordinates[num1], coordinates[num2])
                if bond_check(distance) is True:
                    print(f'{symbols[num1]} to {symbols[num2]} : {distance}')
                
                






O to H1 : 0.9690005374652793
O to H2 : 0.9690003348647513
